name: Run on New Release

on:
  release:
    types: [published]

jobs:
  on-release-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract schema name from tag
        id: extract
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          SCHEMA_NAME=$(echo "$TAG_NAME" | cut -d'-' -f1)
          echo "schema_name=$SCHEMA_NAME" >> $GITHUB_OUTPUT

      - name: JSON Schema Check
        uses: kit-data-manager/json-schema-check-action@v0.0.4
        with:
          schemaPath: "${{ steps.extract.outputs.schema_name }}.json"
          token: ${{ secrets.GITHUB_TOKEN }}
