name: Run on New Release

on:
  release:
    types: [published]  # Triggers only when a release is published

jobs:
  on-release-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print release info
        run: |
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Release name: ${{ github.event.release.name }}"
          echo "Published by: ${{ github.actor }}"
          echo "Published by: ${{ github.event.release.upload_url }}"
          
